require "spec_helper"

describe Shield do
  
  before :each do
    @shield = Shield.new("TestShield",10,10,1)
  end
  
  describe '#shieldStatus' do
    it "should be 10 by default" do
      @shield.shieldStatus.should == 10
    end
    
    it "should be 5 if damaged by 50%" do
      @shield.takesDamage 0.5
      @shield.shieldStatus.should == 5
    end
    
    it "should be 0 if off" do
      @shield.off
      @shield.shieldStatus.should == 0
    end    
  end
  
  describe '#takeShieldDamage' do
    
    it "should be 9 if hit with one point of damage" do
      @shield.takeShieldDamage 1
      @shield.shieldStatus.should == 9
    end
  end  
  
  describe '#regenerate' do
    it "should be 9 if regenerated by 1" do
      @shield.takeShieldDamage 2
      @shield.regenerate
      @shield.shieldStatus.should == 9
    end
    
    it "should be 0 if hit full and reloading" do
      @shield.takeShieldDamage 10
      @shield.regenerate
      @shield.shieldStatus.should == 0
    end
    
    it "should be 1 if it had enough time stabilize the shield" do
      @shield.takeShieldDamage 10
      6.times do
        @shield.regenerate
      end
      @shield.shieldStatus.should == 1
    end    
  end  
end